var shipNames = [
	"Yagua",
	"Bouncer",
	"Lysaker",
	"Arthur C. G. Stone",
	"Costa Tropicale",
	"Castillo Tordesillas",
	"Taymouth Castle",
	"Dordrecht",
	"Tantalus",
	"Surada",
	"Augustus Thomas",
	"Imperoyal",
	"Mana Kai",
	"Ngapuhi",
	"Darleydale H.",
	"Kimball Harlow",
	"Bracondale",
	"Damfoss",
	"Fotia",
	"Pretty Lady III",
	"Caldwell",
	"Fukurokuju Maru",
	"Inie",
	"Dimitris",
	"Labotas",
	"Helmuth",
	"Henning B.",
	"Lampas",
	"Lamington",
	"Nuijamaa",
	"Flinders",
	"Actief",
	"Koan Maru No.2",
	"Jaoobus",
	"Falcon",
	"Vaagholm",
	"Doonie Brass",
	"Ebb",
	"Gaelie",
	"Hohenlinden",
	"Lake Pistol",
	"Darent",
	"Macbrae",
	"Blew-BY-U",
	"Mac Sin",
	"Jean et Jacques",
	"Scholarship",
	"Massachusetts",
	"British Duchess",
	"Pickin' Daisies",
	"Santa Maria"
];